### PR TITLE
Bug fixing

### PR DESCRIPTION
**Pull request by sammyfreg**
Editor can now close without crash

### CODE REVIEW

**Comment by sammyfreg** [comment]
Somehow, it pulled the various checkin history. Only the last commit (Bugfix : 0481be6 ) matter, everything else should be the same

**Comment by segross** [comment]
Hey. I've seen your response in the other thread but I will continue here. Thank you for looking into this and for the quick fix.

Yes, that is strange. Not sure why that happened. I'll see how it looks on my side. Possibly it will figure out that those are the same CLs.

**Comment by sammyfreg** [comment]
Probably because of the squash checkin. It seems to be having no merge conflicts.

**Comment by segross** [comment]
Great thanks for the fix @sammyfreg!

It all merged nicely and despite the confusion with changes it looks good in the actual CL. Thanks for the heads up.
And about why so many changes. I think that the likely reason might be the fact that the BugFixing was branched from the master and the first change was not yet merged there.

**Pull request merged**
